# config.yaml
world_model: "warehouse"
robot_group_args:
  - robot_name: "qrb_amr_mini_robot"          # name of robot entity
    robot_base_ns: "qrb_robot_base"           # namespace of robot base model
    enable_laser: "true"                     # enable/Disable lidar sensor in simulator
    enable_imu: "true"                       # enable/Disable IMU sensor in simulator
    enable_rgb_camera: "true"                # enable/Disable RGB camera sensor in simulator
    enable_depth_camera: "true"              # enable/Disable depth camera sensor in simulator
    initial_x: "0.0"                          # robot model's initial position in the world
    initial_y: "0.0"
    initial_z: "0.0"
    initial_roll: "0.0"
    initial_pitch: "0.0"
    initial_yaw: "0.0"