# rgb camera parameters
sensor_name: "rgb_camera"
update_rate: 20
camera:
  horizontal_fov: 1.500983
  camera_info_topic: "camera/camera_info"
  image:
    width: 1280
    height: 720
    format: "RGB_INT8"
  clip:
    near: 0.02
    far: 100
always_on: 1
visualize: "true"
enable_metrics: "true"
topic: "camera/image_raw"
